CREATE TABLE "pacal_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pacal_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timestamp" timestamp with time zone NOT NULL,
	"description" text,
	"weight_g" real,
	"calories" real,
	"estimation_status" text DEFAULT 'estime' NOT NULL,
	"condition" text NOT NULL,
	"note" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "entry_timestamp_idx" ON "pacal_entry" USING btree ("timestamp");